const getGcpData = [
    {
          co2e: 82.366776,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_east_1",
            uuid: "3493fa51-bd68-4e0c-b093-55c86ae0d086",
            id: "cpu-provider_gcp-region_asia_east_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "TW",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 82.366776,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 95.307924,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_east_2",
            uuid: "98548b98-486f-4211-875a-7141ddd38b3d",
            id: "cpu-provider_gcp-region_asia_east_2",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "HK-HKG",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 95.307924,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 79.778196,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_northeast_1",
            uuid: "3c174071-a124-40bc-b1e8-3e75312deeb0",
            id: "cpu-provider_gcp-region_asia_northeast_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "JP-TYO",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 79.778196,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 79.778196,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_northeast_2",
            uuid: "81f4f04b-7b12-49f2-8f62-0720afd11afd",
            id: "cpu-provider_gcp-region_asia_northeast_2",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "JP-OSA",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 79.778196,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 82.214352,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_northeast_3",
            uuid: "41299af6-3af9-4c1e-a2c0-cc6138a00cd1",
            id: "cpu-provider_gcp-region_asia_northeast_3",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "KR-SEL",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 82.214352,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 110.07597,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_south_1",
            uuid: "caec7f71-7cf4-4261-9d12-0ebef1ba3652",
            id: "cpu-provider_gcp-region_asia_south_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "IN-BOM",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 110.07597,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 75.058746,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_southeast_1",
            uuid: "4f7fceef-a18e-43e5-86ed-5e640022960f",
            id: "cpu-provider_gcp-region_asia_southeast_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "SG-SIN",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 75.058746,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 117.535986,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_asia_southeast_2",
            uuid: "ac8bac46-5895-4553-b141-3497901580a1",
            id: "cpu-provider_gcp-region_asia_southeast_2",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "ID-JKT",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 117.535986,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 110.38038,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_australia_southeast_1",
            uuid: "994625a1-b77e-4bef-ba35-73f877472428",
            id: "cpu-provider_gcp-region_australia_southeast_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "AU-SYD",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 110.38038,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 27.557208000000003,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_north_1",
            uuid: "c67b4a8b-a4db-4f6c-9471-fb424d4e6ffe",
            id: "cpu-provider_gcp-region_europe_north_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "FI-HMN",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 27.557208000000003,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 29.84094,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_west_1",
            uuid: "8ea8ef09-eaf2-4255-8939-766d51fa4898",
            id: "cpu-provider_gcp-region_europe_west_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "BE-GHI",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 29.84094,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 39.127854,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_west_2",
            uuid: "7bf40335-e921-496b-9489-b97335014c26",
            id: "cpu-provider_gcp-region_europe_west_2",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "GB-LON",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 39.127854,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 48.567192,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_west_3",
            uuid: "17c56baa-49b9-4c65-b8d0-569e8d6bca8a",
            id: "cpu-provider_gcp-region_europe_west_3",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "DE-FRA",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 48.567192,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 72.165756,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_west_4",
            uuid: "2e3724d8-1073-44d5-88a0-f5eec737c6ad",
            id: "cpu-provider_gcp-region_europe_west_4",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "NL-EEM",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 72.165756,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 4.41504,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_europe_west_6",
            uuid: "9c57629a-eee6-4d6a-a893-8fb23c662e2b",
            id: "cpu-provider_gcp-region_europe_west_6",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "CH-ZRH",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 4.41504,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 21.771666,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_northamerica_northeast_1",
            uuid: "c0096b44-6932-471e-ace5-8470cb2e1436",
            id: "cpu-provider_gcp-region_northamerica_northeast_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "CA-MTR",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 21.771666,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 16.594944,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_southamerica_east_1",
            uuid: "c29a05b9-ce04-450c-becd-6aff7ff6e9df",
            id: "cpu-provider_gcp-region_southamerica_east_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "BR-SAO",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 16.594944,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 72.927,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_central_1",
            uuid: "c9d26938-a7bf-4980-945b-9002ec359f76",
            id: "cpu-provider_gcp-region_us_central_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-IA",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 72.927,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 76.1244,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_east_1",
            uuid: "2bdb6120-30c7-4d93-ae32-a58a55d5377e",
            id: "cpu-provider_gcp-region_us_east_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-SC",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 76.1244,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 58.311378000000005,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_east_4",
            uuid: "523aa3b8-81d2-468b-bcf2-846f48d86266",
            id: "cpu-provider_gcp-region_us_east_4",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-VA",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 58.311378000000005,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 17.813022,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_west_1",
            uuid: "55659c89-b953-42c3-b6ae-9120f4a8e52f",
            id: "cpu-provider_gcp-region_us_west_1",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-OR",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 17.813022,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 37.75779,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_west_2",
            uuid: "49daebb0-198c-4a87-997d-d398ad2e228b",
            id: "cpu-provider_gcp-region_us_west_2",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-LAX",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 37.75779,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 85.411752,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_west_3",
            uuid: "9aefc29c-ad34-4c8f-a414-92b941d7847f",
            id: "cpu-provider_gcp-region_us_west_3",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-SLC",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 85.411752,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          },
        },
        {
          co2e: 74.754336,
          co2e_unit: "kg",
          co2e_calculation_method: "ar4",
          co2e_calculation_origin: "source",
          emission_factor: {
            activity_id: "cpu-provider_gcp-region_us_west_4",
            uuid: "553af056-1ddb-4587-a849-a4b924f223e7",
            id: "cpu-provider_gcp-region_us_west_4",
            access_type: "public",
            source: "CCF",
            year: "2021",
            region: "US-LAS",
            category: "Cloud Computing - CPU",
            lca_activity: "use_phase",
            data_quality_flags: ["notable_methodological_variance"],
          },
          constituent_gases: {
            co2e_total: 74.754336,
            co2e_other: null,
            co2: null,
            ch4: null,
            n2o: null,
          }
        }
      ]
  

var dic={};
var lis=getGcpData;
//console.log(lis[0])
for(let i=0;i<lis.length;i++)
{
    dic[lis[i]['emission_factor']['region']]=lis[i]['emission_factor']['activity_id'];
}
console.log(dic);